dist: trusty
language: node_js
node_js:
- '5.12'
before_install:
- openssl aes-256-cbc -K $encrypted_649f128e279d_key -iv $encrypted_649f128e279d_iv
  -in deploy_key.enc -out deploy_key -d
before_script:
- npm install
script:
- npm run docs
- npm run build
after_success:
- |
  if ([ ! -z "$TRAVIS_TAG" ]) &&
    [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    echo "Deploying $TRAVIS_TAG to server"
    chmod 600 deploy_key
    mv deploy_key ~/.ssh/id_rsa
    touch dist/version.json
    echo "{ \"version\": \"$TRAVIS_TAG\" }" > dist/version.json
    tar -czf transfer.tgz dist
    scp -o "StrictHostKeyChecking no" transfer.tgz jenkins@159.203.18.58:/var/www/meditation-plus
    ssh -o "StrictHostKeyChecking no" jenkins@159.203.18.58 'cd /var/www/meditation-plus; cp config/config.json ./; rm -rf !(client|config.json|transfer.tgz); tar -xzf transfer.tgz  --strip 1; mv config.json config/config.json; rm transfer.tgz'
  fi
