notifications:
  email: false
dist: trusty
language: node_js
services:
  - mongodb
node_js:
  - '7'
before_install:
  - openssl aes-256-cbc -K $encrypted_649f128e279d_key -iv $encrypted_649f128e279d_iv
    -in deploy_key.enc -out deploy_key -d
script:
  - cp src/config/config.json.travis src/config/config.json
  - yarn lint && yarn test && yarn docs && yarn build
  - cp -R src/app/helper/mail-templates dist/app/helper/mail-templates
after_success:
  - sh deploy.sh
