notifications:
  email: false
dist: trusty
language: node_js
services:
  - mongodb
node_js:
  - '5'
  - '6'
before_install:
  - openssl aes-256-cbc -K $encrypted_649f128e279d_key -iv $encrypted_649f128e279d_iv
    -in deploy_key.enc -out deploy_key -d
before_script:
  - npm install
script:
  - cp src/config/config.json.travis src/config/config.json
  - npm run lint
  - npm run test
  - npm run docs
  - npm run build
after_success:
  - sh deploy.sh
